---
name: "RandomContent"
guid: "2e3a18aa-b069-4e56-8e0d-d431f7745a1c"
version: "1.0.0.0"
targetAbi: "10.9.0.0"
framework: "net8.0"
overview: "Open a random movie or series from your library"
description: >
  Adds a button next to search that opens a random
  movie or series from your Jellyfin library.
category: "General"
owner: "jellyfin"
artifacts:
- "Jellyfin.Plugin.RandomContent.dll"
changelog: >
  changelog
